#remote_theme: mmistakes/minimal-mistakes@4.27.3
remote_theme: jekyll/minima

plugins:
 - jekyll-remote-theme
 - jekyll-include-cache

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true 
google_analytics: G-5VZDLTCMDW
